name: Deploy to Workshop

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    if: github.repository == 'ACF-Team/precision-alignment'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: project

      - name: Upload to Workshop
        uses: CFC-Servers/gmod-upload@master
        with:
          id: 3600007065
          changelog: "${{ github.event.head_commit.message }}"
          title: "Precision Alignment Retooled"
          type: "tool"
          tag1: "build"
          tag2: "scenic"
          tag3: "realism"
        env:
          STEAM_USERNAME: ${{ secrets.ACF_STEAM_ACCOUNT }}
          STEAM_PASSWORD: ${{ secrets.ACF_STEAM_PASSWORD }}
